### ISSUE TITLE
Feature request: #ifdef/#ifndef one-liners

### ISSUE THREAD

**Issue by htfv** [raydac/java-comment-preprocessor#11]
We are migrating our codebase from some old persistence technology to JPA. We have to support both technologies in the transition phase. After evaluating some options, we chose JCP to build our code for one of the persistence technologies.

JCP works for us perfectly in most cases, the only trouble is IDE (which is not JCP's fault of course). Usually we use only `#ifdef JPA` directive. IDE ignores the directive and we effectively get JPA code compiled. There are however some cases where we have to use something similar to the following:

    //#ifdef JPA
        doOneThing();
    //#else
        doOtherThing();
    //#endif

If there are some workarounds for the case above, the following is even worse:

    class SomeClass
    //#ifdef JPA
            extends OneBase
    //#else
            extends OtherBase
    //#endif

I have an idea for one-liners:

    //#ifdef JPA
        doOneThing();
    //#endif
    //#ifndef JPA: doOtherThing();

    //#ifdef JPA
        doOneThing();
    //else: doOtherThing();
    //#endif

IDE will recognize the second part as comment and will ignore it. Do you think it's possible to have something like this?

**Comment by raydac** [comment]
may be to use //$$ directive?
```
//#ifdef JPA
        extends OneBase
//#else
        //$$ extends OtherBase
//#endif
```
it will make code recognizable by IDE and preprocessor automatically removing //$$ and //$
```
    /$ replace macroses in following text and out result

     //#local VAR="hello"
     //$ var contains /*$VAR$*/
     the output file fill have only " var contains hello"

    //$$ works like //$ but without macros replacement

     //#local VAR="hello"
     //$$ var contains /*$VAR$*/
     the output file fill have only " var contains /*$VAR$*/"
```

**Comment by htfv** [comment]
Oh. I read through the documentation but somehow missed that I could use this directive for my case. It should do it. Thank you for quick response and great tool.
