### ISSUE TITLE
Maven plugin fails if the source folder is missing

### ISSUE THREAD

**Issue by htfv** [raydac/java-comment-preprocessor#12]
Typical Maven plugins skip missing source folders (compiler, resources, surefire, etc). This allows configuring them once in a parent POM or lifecyle. JCP fails the build if the source folder is missing.

Use case: we are using JCP in a big project with over 500 modules. Currently we define 2 executions: one for main and one for test sources. We want to configure JCP in the common parent POM to enable it in all modules by default, but it does not always work, because some modules do not have test sources.

Please make JCP Maven plugin ignore missing sources folders, or add a configuration parameter to ignore missing source folders.

I can implement the change and make a pull request if that will speed up things.

**Comment by raydac** [comment]
ok, I will check

**Comment by raydac** [comment]
I have added boolean parameter 'ignoreMissingSources' which is false by default
```
<ignoreMissingSources>true</ignoreMissingSources>
```
if such flag is set then missing source folders will be ignored and error will not be thrown

**Comment by htfv** [comment]
I tested it and it works. Thank you for quick response. When can we expect release?

**Comment by raydac** [comment]
I have published the snapshot version in the snapshot repository (which described in readme), if all is ok and there is not new ideas and issues during one-two weeks then I will release the plugin in the maven central

**Comment by raydac** [comment]
6.1.1 has been published in maven central
