### ISSUE TITLE
Add a skip parameter to the preprocess goal

### ISSUE THREAD

**Issue by htfv** [raydac/java-comment-preprocessor#13]
Many Maven plugins have a skip parameter with an associated property to skip the execution. Having such parameter and property is convenient as it allows a) temporarily disabling plugin in command line by adding a -D option; b) configuring plugin in a parent POM and redefining a property in a child POM to change behavior (enable or disable execution).

Please add such parameter to the JCP Maven plugin.

I can create a pull request if it helps.

**Comment by raydac** [comment]
I have added boolean `skip` parameter which also can be set through property `-Djcp.preprocess.skip=true`
to skip execution of plugin, just add
```
<skip>true</skip>
```

**Comment by htfv** [comment]
I tested it and it works. Thank you for quick response.
