### ISSUE TITLE
Can I build/run jcp without meta-* dependencies?

### ISSUE THREAD

**Issue by praiskup** [raydac/java-comment-preprocessor#19]
In fedora, we don't have the meta-* jars:
https://bugzilla.redhat.com/show_bug.cgi?id=1584114

Is there a possibility to make that meta-* stuff optional for jcp?

**Comment by raydac** [comment]
how do you build the preprocessor? meta packages are published in maven central, fedora has some specific repository?

**Comment by praiskup** [comment]
Yes, we have our own set of (RPM) packages.

**Comment by praiskup** [comment]
That would be much more convenient, yes.

**Comment by raydac** [comment]
and such artifact presented in fedora repository?
```
<groupId>com.google.code.findbugs</groupId>
<artifactId>jsr305</artifactId>
```
is it possible for me to emulate build process to check it ?

**Comment by praiskup** [comment]
> and such artifact presented in fedora repository?

Not yet :-/

> is it possible for me to emulate build process to check it ?

Probably, but it requires some level of experience to have it done quickly; you can try to `docker run -ti fedora:rawhide`, and run RPM build inside (you need the spec file + sources, available in https://src.fedoraproject.org/rpms/java-comment-preprocessor).  But I'd be glad to give try the build instead of you.

**Comment by raydac** [comment]
you can try current snapshot version, I have removed meta dependencies and it can be build with `mvn clean install -P'!metacheck'`

**Comment by praiskup** [comment]
Awesome, it works fine now.  Thanks for the fix, @raydac.

**Comment by praiskup** [comment]
Test-build is here:
https://copr.fedorainfracloud.org/coprs/praiskup/new-java-comment-preprocessor/monitor/

It would be awesome to have a new release with this :-)

**Comment by praiskup** [comment]
Thanks!  I updated fedora package to 6.1.4: https://koji.fedoraproject.org/koji/taskinfo?taskID=27672154

I temporarily downstream reverted 6ca437135e19c7506286458416485b0d6abcbf1c till we have the deps in Fedora (I guess that's a matter of time).
