### ISSUE TITLE
Problem with newer mockito?

### ISSUE THREAD

**Issue by praiskup** [raydac/java-comment-preprocessor#20]
[ERROR] /builddir/build/BUILD/java-comment-preprocessor-6.1.4/src/test/java/com/igormaznitsa/jcp/AbstractMockPreprocessorContextTest.java:[44,52] cannot find symbol
  symbol:   method getArgumentAt(int,java.lang.Class<java.lang.String>)
  location: variable invocation of type org.mockito.invocation.InvocationOnMock
[ERROR] /builddir/build/BUILD/java-comment-preprocessor-6.1.4/src/test/java/com/igormaznitsa/jcp/AbstractMockPreprocessorContextTest.java:[44,124] cannot find symbol
  symbol:   method getArgumentAt(int,java.lang.Class<java.lang.Throwable>)
  location: variable invocation of type org.mockito.invocation.InvocationOnMock

Seems to be related to mockito/mockito/issues/945

**Comment by raydac** [comment]
yes, new mockito version can't be used with 6.1.4, I have reworked project structure and fixed build process in 7.0.0-SNAPSHOT to be compatible with mockito and java 11
