### ISSUE TITLE
Maven property override in command line

### ISSUE THREAD

**Issue by gwenn** [raydac/java-comment-preprocessor#30]
It seems that override from command line is ignored:
```sh
mvn -Dmy.property=false compile
```
```xml
  <properties>
    <my.property>true</my.property>
  </properties>
```
```java
	//#if mvn.project.property.my.property == "true"
...
	//#endif
```
I uses a [profile](https://github.com/gwenn/sqlite-jna/blob/master/pom.xml#L184) to bypass.

**Comment by raydac** [comment]
good point, I just importing property value directly from project properties field but to process overriding values it is needed to be more complex one, will fix

**Comment by raydac** [comment]
I have fixed it in 7.0.5-SNAPSHOT

**Comment by gwenn** [comment]
Validated in 7.0.5-SNAPSHOT
Should I close the current issue ?
Thanks.

**Comment by raydac** [comment]
you can close if all is ok
