### ISSUE TITLE
Implement custom action preprocessor extension for plugins and cli

### ISSUE THREAD

**Issue by mintdaniel42** [raydac/java-comment-preprocessor#48]
I've searched through half of the code in order to understand how the //#action directive works. As far as I understood one can plug in your own preprocessing macros through extending the PreprocessorExtension. But how can I set my own extension class so that the preprocessor uses it? Neither the [documap](https://raw.githubusercontent.com/raydac/java-comment-preprocessor/master/assets/documap.png) nor the gradle task give any information about that. In addition to that, a PreprocessorContext.setPreprocessorExtension(PreprocessorExtension) method is defined but never used (at least I couldn't find any usages with IntelliJ decompiler & find usages). Is the feature not ready yet or did I just miss something?

**Comment by raydac** [comment]
it is very old mechanism developed 20+ years ago to provide some point where custom code can be called
to use it just before execution, set into created context your class as an extension as shown in [com.igormaznitsa.jcp.usecases.UserFunctionTest](https://github.com/raydac/java-comment-preprocessor/blob/master/jcp/src/test/java/com/igormaznitsa/jcp/usecases/UserFunctionTest.java)
```
 context.setPreprocessorExtension(instanceOfYourClass);
```
then your registered extension should be called during preprocessing

**Comment by mintdaniel42** [comment]
Okay thanks, but how can I use this with a build tool?

**Comment by raydac** [comment]
it was developed for use preprocessor programmatically as part of build process, for use on application level it needs improvements

**Comment by mintdaniel42** [comment]
Oh okay but thanks anyway

**Comment by raydac** [comment]
anyway it is a good point, I will provide way to register a class as action preprocessor extension in plugins

**Comment by mintdaniel42** [comment]
Yoo, that's cool. Thank you! I'll take a look into it!

**Comment by raydac** [comment]
the feature is released in 7.1.2
