### ISSUE TITLE
A global variable is unknown when preprocessing xml

### ISSUE THREAD

**Issue by guy7373** [raydac/java-comment-preprocessor#6]
I am using jcp with gradle in android studio
I declared a global variable (TEST_VAR) in preprocess.gradle.
When preprocessing the source TEST_VAR is known... 
When preprocessing the resources TEST_VAR is unknown and an exception is thrown.
When declaring TEST_VAR as global in the xml the file is preprocessed correctly.

**Comment by raydac** [comment]
do you use the gradle script from the wiki  to preprocess your android project?

**Comment by raydac** [comment]
I have edited the wiki page and added some extra info about workaround through config file with defined global variables

**Comment by guy7373** [comment]
Works

Thanks you :)
