### ISSUE TITLE
Feature Suggestion: Allow whitespace between // and # in directives

### ISSUE THREAD

**Issue by bjakke** [raydac/java-comment-preprocessor#9]
Hi,

This tool/plugin is great! The only minor inconvenience is that the directives must be `//#directive` and at least based on my tests they wont work if there is whitespace between the `//` and `#`, i.e. `// #directive`. I'm not sure how common it is but at least in eclipse standard java formatter convetions it is to add a space between the `//` and rest of the comment. I would assume it is used quite a lot (either configured as on-save-action or executed separately). 

This means I need to disable that part of the formatter (which in practise means I need to create a custom one as the default cannot be edited). It also requires everyone else to be aware of this issue if they are using any auto formatting in a shared project and adding some "safety checks" to the build to check that the processing has happened. 

It would be great if in the future there would be an option to allow that whitespace to exist (probably by default off to keep backward compatibility). Alternatively supporting e.g. `// //#directive` would work too.

Bjakke

**Comment by raydac** [comment]
good idea, thanks, I will think how to implement such feature

**Comment by raydac** [comment]
I made some changes and such functionality is presented in 6.1.0-SNAPSHOT

**Comment by bjakke** [comment]
Great!
